apiVersion: v1
kind: Namespace
metadata:
  name: guardian-operator-system
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guardian-operator-controller-manager
  namespace: guardian-operator-system
